return [[
group;subgroup;name;xm;recipes;specials;prerequisites;count;ingredients;time;;icon
part;mechanical;"parts_1";true;{"bearing-1", "gear-3", "rod-2", "shaft-1", "mechanism-1", "wheel-1", "steel-axe"};nil;{"machine-tool_0", "graphite-washing"};20;{{"science-pack-1", 1}};15;;"__xander-mod__/graphics/technology/part/parts_1.png"
part;mechanical;"parts_2";true;{"bearing-2", "gear-4", "rod-3", "shaft-2", "mechanism-2", "wheel-2"};nil;{"parts_1", "forging-alloy-a", "oil-processing", "lead-brass"};200;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;"__xander-mod__/graphics/technology/part/parts_2.png"
part;mechanical;"parts_3";true;{"bearing-3", "rod-4", "shaft-3", "mechanism-3"};nil;{"parts_2", "forging-titanium", "silicon-nitride", "plastics"};400;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};60;;"__xander-mod__/graphics/technology/part/parts_3.png"
part;mechanical;"tooling_1";true;{"tooling-1-b"};nil;{"steel-processing", "acheson-process", "phenolic-resin"};20;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;"__xander-mod__/graphics/technology/part/tooling_1.png"
part;mechanical;"tooling_2";true;{"tooling-2", "axe-5"};nil;{"tooling_1", "forging-alloy-a", "tungsten-cermet"};150;{{"science-pack-1", 1}, {"science-pack-2", 1}};45;;"__xander-mod__/graphics/technology/part/tooling_2.png"
part;mechanical;"tooling_3";true;{"tooling-3", "tooling-1-c", "axe-6"};nil;{"tooling_2", "optics_3", "epoxy-resin"};300;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};60;;"__xander-mod__/graphics/technology/part/tooling_3.png"
part;mechanical;"engine";false;{"engine-unit"};nil;{"parts_1", "plumbing-steel", "rubber-a"};unchanged;unchanged;unchanged;;unchanged
part;mechanical;"machines_1";true;nil;nil;{"electric-engine"};15;{{"science-pack-1", 1}};10;;"__xander-mod__/graphics/technology/production/automation-1.png"
part;mechanical;"machines_2";true;nil;nil;{"machines_1", "motor_2", "tooling_2", "forging-stainless"};150;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;"__xander-mod__/graphics/technology/production/automation-3.png"
part;mechanical;"machines_3";true;nil;nil;{"machines_2", "motor_3", "tooling_3", "forging-superalloy"};400;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};60;;"__xander-mod__/graphics/technology/production/automation-4.png"
part;mechanical;"flying";false;unchanged;nil;{"parts_2", "battery_2", "forging-aluminum"};unchanged;unchanged;unchanged;;unchanged
part;mechanical;"flying_2";true;nil;nil;{"flying", "battery_3", "fiber-carbon", "machines_3"};500;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"high-tech-science-pack", 1}};45;;"__base__/graphics/technology/flying.png"
part;electromagnetic;"electricity";true;{"steam-engine", "insulator-1-a", "small-electric-pole"};nil;{"induction_1"};10;{{"science-pack-0", 1}};20;;"__xander-mod__/graphics/technology/part/electricity.png"
part;electromagnetic;"insulator_2";true;{"insulator-1-b", "insulator-2-a"};nil;{"electricity", "glass-b"};150;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;"__xander-mod__/graphics/technology/part/insulator_2.png"
part;electromagnetic;"insulator_3";true;{"insulator-2-b"};nil;{"insulator_2", "silicon-nitride"};450;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}, {"high-tech-science-pack", 1}};60;;"__xander-mod__/graphics/technology/part/insulator_3.png"
part;electromagnetic;"induction_1";true;{"coil-1-a", "electric-engine-unit", "science-pack-1"};nil;{"reactor_0", "graphite-washing"};10;{{"science-pack-0", 1}};15;;"__xander-mod__/graphics/technology/part/induction.png"
part;electromagnetic;"induction_2";true;{"coil-1-b", "sheet-steel", "coil-2"};nil;{"induction_1", "phenolic-resin"};200;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;"__xander-mod__/graphics/technology/part/induction.png"
part;electromagnetic;"induction_3";true;{"sheet-mu", "coil-3"};nil;{"induction_2", "cobalt-refining", "re-refining", "epoxy-resin"};350;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};45;;"__xander-mod__/graphics/technology/part/induction.png"
part;electromagnetic;"electric-engine";false;{"motor-1-b", "transformer-1"};nil;{"induction_1", "parts_1", "electronics"};unchanged;{{"science-pack-1", 1}};unchanged;;unchanged
part;electromagnetic;"motor_2";true;{"motor-2", "transformer-2"};nil;{"induction_2", "parts_2", "advanced-electronics"};200;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}};30;;"__base__/graphics/technology/electric-engine.png"
part;electromagnetic;"motor_3";true;{"motor-3", "transformer-3"};nil;{"induction_3", "parts_3", "insulator_2", "advanced-electronics-2"};350;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};45;;"__base__/graphics/technology/electric-engine.png"
part;electromagnetic;"battery";false;{"battery", "battery-1"};nil;{"plastics", "lead-refining", "sulfuric-acid-a", "electronics"};unchanged;unchanged;unchanged;;unchanged
part;electromagnetic;"battery_2";true;{"cell-2", "battery-2"};nil;{"battery", "silver-refining", "electrolysis-salt-water", "zinc-refining"};300;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}};60;;"__xander-mod__/graphics/technology/part/battery_2.png"
part;electromagnetic;"battery_3";true;{"cell-3", "battery-3"};nil;{"battery_2", "activated-carbon", "organics_3", "advanced-lithium"};500;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"high-tech-science-pack", 1}};60;;"__base__/graphics/technology/battery.png"
part;electromagnetic;"optics";false;{"crystal-quartz", "boule-ruby", "crystal-ruby"};nil;{"glass-b", "chromium-refining", "aluminum-refining", "acheson-process"};200;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;unchanged
part;electromagnetic;"optics_2";true;{"boule-corundum", "crystal-corundum"};nil;{"optics"};450;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};30;;"__base__/graphics/technology/optics.png"
part;electromagnetic;"optics_3";true;{"boule-diamond", "crystal-diamond", "boule-yag", "crystal-yag"};nil;{"optics_2", "silicon-nitride", "re-refining"};700;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}, {"high-tech-science-pack", 1}};60;;"__base__/graphics/technology/optics.png"
part;electromagnetic;"laser";false;{"lasing-1"};nil;{"optics", "machines_2", "lamp_1"};250;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}};45;;unchanged
part;electromagnetic;"laser_2";true;{"lasing-2"};nil;{"laser", "optics_2", "machines_3", "lamp_2"};500;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};60;;"__xander-mod__/graphics/technology/part/laser_2.png"
part;electromagnetic;"laser_3";true;{"lasing-3"};nil;{"laser_2", "optics_3"};900;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}, {"high-tech-science-pack", 1}};60;;"__xander-mod__/graphics/technology/part/laser_3.png"
part;data;"wire_1";true;{"wire-copper", "wire-tinned", "solder-flux-a", "wire-solder-1"};nil;{"soldering_1"};30;{{"science-pack-1", 1}};15;;"__xander-mod__/graphics/technology/data/wire_1.png"
part;data;"wire_2";true;{"wire-tungsten", "wire-gold", "sheet-gilded"};nil;{"wire_1", "gold-refining", "silver-refining", "machine-tool_1"};150;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;"__xander-mod__/graphics/technology/data/wire_2.png"
part;data;"substrate_1";true;{"metallized-1"};nil;{"machine-tool_0", "reactor_0"};20;{{"science-pack-1", 1}};15;;"__xander-mod__/graphics/technology/data/substrate_1.png"
part;data;"substrate_2";true;{"sheet-tinned", "metallized-2", "etched-2-a", "circuit-1-b"};nil;{"substrate_1", "wire_1", "phenolic-resin", "nitric-acid-a"};200;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;"__xander-mod__/graphics/technology/data/substrate_2.png"
part;data;"substrate_3";true;{"metallized-3", "etched-3"};nil;{"substrate_2", "wire_2", "epoxy-resin", "glass-b"};500;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}};60;;"__xander-mod__/graphics/technology/data/substrate_3.png"
part;data;"soldering_1";true;{"solder-1-plate-a"};nil;{"substrate_1"};10;{{"science-pack-1", 1}};10;;"__xander-mod__/graphics/technology/data/soldering_1.png"
part;data;"soldering_2";true;{"solder-1-plate-b", "solder-flux-b"};nil;{"soldering_1", "advanced-material-processing-2", "haber-process"};150;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}};30;;"__xander-mod__/graphics/technology/data/soldering_2.png"
part;data;"soldering_3";true;{"solder-2-plate", "wire-solder-2"};nil;{"soldering_2"};300;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}};30;;"__xander-mod__/graphics/technology/data/soldering_3.png"
part;data;"semiconductors_1";true;{"wafer-1", "wafer-2"};nil;{"silicon-boule-a", "sodium-processing"};200;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;"__xander-mod__/graphics/technology/data/semiconductors.png"
part;data;"semiconductors_2";true;{"wafer-3"};nil;{"semiconductors_1", "laser", "silicon-nitride", "organics_2"};500;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}};60;;"__xander-mod__/graphics/technology/data/semiconductors.png"
part;data;"electronics";false;{"components-1-a", "electronic-circuit", "control-1"};nil;{"soldering_1"};50;{{"science-pack-1", 1}};20;;unchanged
part;data;"advanced-electronics";false;{"components-2-a", "advanced-circuit", "control-2", "science-pack-3"};nil;{"electronics", "substrate_2", "tungsten-refining"};200;{{"science-pack-1", 1}, {"science-pack-2", 1}};30;;unchanged
part;data;"advanced-electronics-2";false;{"components-3", "components-2-b", "processing-unit", "control-3", "high-tech-science-pack"};nil;{"advanced-electronics", "substrate_3", "semiconductors_2", "soldering_2"};400;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}};45;;unchanged
part;rocket;"rocket-fuel";true;{"rocket-fuel"};nil;{"advanced-oil-processing", "haber-process", "electrolysis-water-b", "advanced-lithium"};1000;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};45;;"__xander-mod__/graphics/technology/part/rocket-fuel.png"
part;rocket;"rocket-structure";true;{"low-density-structure"};nil;{"machines_3", "epoxy-resin", "fiber-carbon", "forging-aluminum"};1000;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};45;;"__xander-mod__/graphics/technology/part/rocket-structure.png"
part;rocket;"rocket-control";true;{"rocket-control-unit"};nil;{"machines_3", "speed-module", "effectivity-module", "laser_3"};1000;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}, {"high-tech-science-pack", 1}};45;;"__xander-mod__/graphics/technology/part/rocket-control.png"
part;rocket;"rocket-engine";true;{"rocket-thermal"};nil;{"machines_3", "silicon-nitride", "brick-zirconia", "forging-zirconium"};1000;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}, {"high-tech-science-pack", 1}};45;;"__xander-mod__/graphics/technology/part/rocket-engine.png"
part;rocket;"rocket-mechanism";true;{"rocket-mechanism"};nil;{"machines_3", "pump_3", "explosives", "battery_3"};1000;{{"science-pack-1", 1}, {"science-pack-2", 1}, {"science-pack-3", 1}, {"production-science-pack", 1}};45;;"__xander-mod__/graphics/technology/part/rocket-mechanism.png"
]]